public enum SoundClipTrigger
{
    OnOpenBook,
    OnCloseBook,
    OnCastThrow,
    OnPickEyes,
    OnPickHooks,
    OnPickPlastic,
    OnPaint,
    OnLureTurn,
    OnBlockCarve,
    OnBlockHit,
    OnSeagulls,
    OnDiscardEye,
    OnDiscardHook,
    OnDiscardPlastic,
    OnBookPageChange,
    OnFishAlert,
    OnFishCaught,
    OnLureTrash,
    OnUiClick,
    OnUiError
}
